
export const DAILY_SALE_REQUEST="DAILY_SALE_REQUEST"
export const DAILY_SALE_SUCCESS="DAILY_SALE_SUCCESS"
export const DAILY_SALE_FAIL="DAILY_SALE_FAIL"

export const WEEKLY_SALE_REQUEST="WEEKLY_SALE_REQUEST"
export const WEEKLY_SALE_SUCCESS="WEEKLY_SALE_SUCCESS"
export const WEEKLY_SALE_FAIL="WEEKLY_SALE_FAIL"

export const MONTHLY_SALES_REQUEST="MONTHLY_SALES_REQUEST"
export const MONTHLY_SALES_SUCCESS="MONTHLY_SALES_SUCCESS"
export const MONTHLY_SALES_FAIL="MONTHLY_SALES_FAIL"
export const YEARLY_SALES_REQUEST="YEARLY_SALES_REQUEST"
export const YEARLY_SALES_SUCCESS="YEARLY_SALES_SUCCESS"
export const YEARLY_SALES_FAIL="YEARLY_SALES_FAIL"

export const CUMULATIVE_SALE_REQUEST="CUMULATIVE_SALE_REQUEST"
export const CUMULATIVE_SALE_SUCCESS="CUMULATIVE_SALE_SUCCESS"
export const CUMULATIVE_SALE_FAIL="CUMULATIVE_SALE_FAIL"

/*
export const DELETE_SALE_REQUEST="DELETE_SALE_REQUEST"

export const DELETE_SALE_SUCCESS="DELETE_SALE_SUCCESS"
export const DELETE_SALE_FAIL="DELETE_SALE_FAIL"


*/