
export const ADD_BRANCH_REQUEST="ADD_BRANCH_REQUEST"
export const ADD_BRANCH_SUCCESS="ADD_BRANCH_SUCCESS"
export const ADD_BRANCH_FAIL="ADD_BRANCH_FAIL"
export const GET_BRANCH_REQUEST="GET_BRANCH_REQUEST"
export const GET_BRANCH_SUCCESS="GET_BRANCH_SUCCESS"
export const GET_BRANCH_FAIL="GET_BRANCH_FAIL"

export const GET_BRANCHES_REQUEST="GET_BRANCHES_REQUEST"
export const GET_BRANCHES_SUCCESS="GET_BRANCHES_SUCCESS"
export const GET_BRANCHES_FAIL="GET_BRANCHES_FAIL"
export const UPDATE_BRANCH_REQUEST="UPDATE_BRANCH_REQUEST"
export const UPDATE_BRANCH_SUCCESS="UPDATE_BRANCH_SUCCESS"
export const UPDATE_BRANCH_FAIL="UPDATE_BRANCH_FAIL"
export const DELETE_BRANCH_REQUEST="DELETE_BRANCH_REQUEST"

export const DELETE_BRANCH_SUCCESS="DELETE_BRANCH_SUCCESS"
export const DELETE_BRANCH_FAIL="DELETE_BRANCH_FAIL"