export const ADD_TO_CART="ADD_TO_CART";
export const REMOVE_FROM_CART="REMOVE_FROM_CART";
export const ADJUST_CART_ITEM="ADJUST_CART_ITEM";
export const REMOVE_CART_ITEM="REMOVE_CART_ITEM";
export const GET_CART_ITEMS="GET_CART_ITEMS";



