
export const ADD_SALE_REQUEST="ADD_SALE_REQUEST"
export const ADD_SALE_SUCCESS="ADD_SALE_SUCCESS"
export const ADD_SALE_FAIL="ADD_SALE_FAIL"
export const GET_SALE_REQUEST="GET_SALE_REQUEST"
export const GET_SALE_SUCCESS="GET_SALE_SUCCESS"
export const GET_SALE_FAIL="GET_SALE_FAIL"

export const GET_SALES_REQUEST="GET_SALES_REQUEST"
export const GET_SALES_SUCCESS="GET_SALES_SUCCESS"
export const GET_SALES_FAIL="GET_SALES_FAIL"
export const UPDATE_SALE_REQUEST="UPDATE_SALE_REQUEST"
export const UPDATE_SALE_SUCCESS="UPDATE_SALE_SUCCESS"
export const UPDATE_SALE_FAIL="UPDATE_SALE_FAIL"
export const DELETE_SALE_REQUEST="DELETE_SALE_REQUEST"

export const DELETE_SALE_SUCCESS="DELETE_SALE_SUCCESS"
export const DELETE_SALE_FAIL="DELETE_SALE_FAIL"


export const GET_STOREKEEPER_SALES_REQUEST="GET_STOREKEEPER_SALES_REQUEST"
export const GET_STOREKEEPER_SALES_SUCCESS="GET_STOREKEEPER_SALES_SUCCESS"
export const GET_STOREKEEPER_SALES_FAIL="GET_STOREKEEPER_SALES_FAIL"