
export const ADD_SHOP_REQUEST="ADD_SHOP_REQUEST"
export const ADD_SHOP_SUCCESS="ADD_SHOP_SUCCESS"
export const ADD_SHOP_FAIL="ADD_SHOP_FAIL"
export const GET_SHOP_REQUEST="GET_SHOP_REQUEST"
export const GET_SHOP_SUCCESS="GET_SHOP_SUCCESS"
export const GET_SHOP_FAIL="GET_SHOP_FAIL"

export const GET_SHOPS_REQUEST="GET_SHOPS_REQUEST"
export const GET_SHOPS_SUCCESS="GET_SHOPS_SUCCESS"
export const GET_SHOPS_FAIL="GET_SHOPS_FAIL"
export const UPDATE_SHOP_REQUEST="UPDATE_SHOP_REQUEST"
export const UPDATE_SHOP_SUCCESS="UPDATE_SHOP_SUCCESS"
export const UPDATE_SHOP_FAIL="UPDATE_SHOP_FAIL"
export const DELETE_SHOP_REQUEST="DELETE_SHOP_REQUEST"

export const DELETE_SHOP_SUCCESS="DELETE_SHOP_SUCCESS"
export const DELETE_SHOP_FAIL="DELETE_SHOP_FAIL"